### PR TITLE
Own server instead of Apache + many cleaning

### PR DESCRIPTION
**Pull request by jplambert**
We do not want to be run by Apache, so that several keywords calls modify the state of the same PHP session. In addition, not depending upon Apache makes deployment much more easy by minimizing dependencies.

Most parts of the code has been refactored and cleaned up:
- Several classes with clear responsibilities
- Unit tests
- Big methods split into smaller ones
- Handling of errors is made debug-able
- stop_remote_server is implemented

Folders :
- robotremote contains the new code
- robotremote-tests contains the unit tests on this code

Classes are :
- RobotRemoteProtocol configues the xml-rpc lib and handles the 5 methods defined in the Robot Framework Remote protocol; future work awaits to handle complex data structures
- KeywordStore handles the loading of the PHP files containing the keywords, and make them available to the protocol; future work awaits to allow loading several PHP files
- RobotRemoteServer is basically an infinite loop which receives requests, processes them and send back the response
- SocketInterface handles the network part to feed the server

In addition ot this class we find:
- BootstrapRobotRemoteServer.php which actually start the server, getting the requests from network sockets
- DemoRobotRemoteServer.php starts a server on fake data; this is handy to play with the XML-RPC protocol (through writng test cases in the unit test files is recommended to keep tests for regression purpose)

### CODE REVIEW

**Comment by jplambert** [comment]
@MacSim75 Could you please have a look? Thanks in advance :-)

**Comment by daluu** [comment]
Well, thanks for inadvertently informing me about a fork =) I had been meaning to offer a non-Apache dependent version but never got around to it.

**Comment by jplambert** [comment]
Hi @daluu,

If you are interested in reviewing this change :

https://github.com/MacSim75/phrrs/pull/1

Are you using this Robot Framework Remote on a regular basis?

**Comment by jplambert** [comment]
By the way, given how the proposed design abstracts the input and output of the server, it should be easy to optionally wire it back to Apache.

**Pull request closed without merging**
