### PR TITLE
Major overhaul

### PR DESCRIPTION
**Pull request by jplambert**
- phpxmlrpc lib installed with composer instead of manual installation
- Stand-alone server, run by PHP CLI, completely independent of Apache
- Support for any number of files to define keyword implementations
- Support for complex data-types (lists and dictionaries, nested and mixed)
- Keyword implementation output is captured and sent back into Robot Framework logs
- Numerous clean-ups and refactoring, use of classes with clear responsibilities and comprehensive test coverage

Have a look at the README, it have been updated too and should give a rather complete overview of what this PR allows.

### CODE REVIEW

**Comment by jplambert** [comment]
By the way, it looks like it may fix the following issues:
- https://github.com/daluu/phrrs/issues/1 -> Not sure to understand the scope of this issue. In any case, running multiple instances of the remote server is easy as pie as a standalone server: just launch as many instances as you wish, on different ports of course...
- https://github.com/daluu/phrrs/issues/2 -> I honestly hope I have provided enough tests to be very confident in the tool. There is not a big amount of end-to-end tests but I believe that's enough given the unit-level coverage.
- https://github.com/daluu/phrrs/issues/3 -> from what I have seen, it works already. More testing might be handy to make sure of it, would be easy to check given the tools I have put in place. On a personal note, I'd rather go with the remote server as is and debug it later if anybody has any trouble with that kind of stuff...
- https://github.com/daluu/phrrs/issues/4 -> implemented, quite easy given the server is stand-alone and independent of Apache. Was handful to implement end-to-end tests.
- https://github.com/daluu/phrrs/issues/5 -> fixed by this PR; incidentally I see the interesting discussions on the matter, might be interesting to see if my implementation was the right/best way to do it! However even if I did not use any facility provided by the XML-RPC lib, the code is still small and easy to read, so I guess that's OK.
- https://github.com/daluu/phrrs/issues/7 -> duplicate keywords are handled, taking into account only one of them (obviously) and issuing an explicit warning (with the guilty files to make it easy to debug)
- https://github.com/daluu/phrrs/issues/8 -> not relevant after my PR, given the different scheme to define keyword implementation

**Comment by daluu** [comment]
Awesome, I'll review & merge when I get a chance. Great work guys :)

**Comment by jplambert** [comment]
@daluu I guess you did not get the chance to review the PR? :-)

**Comment by daluu** [comment]
Yea, sorry haven't gotten through a full review of the changes. I got part way. Thought it best to go through everything before merging. It's quite a list.

**Comment by daluu** [comment]
@jplambert I just started trying out your master branch, haven't fully reviewed all the code yet. Do you have other users using your version?

There could be more polishing and compatibility work. I came across the following issue:

Running the remote server against the reference implementation [example RF test](https://github.com/robotframework/PythonRemoteServer/blob/master/example/example_tests.robot), the server crashes for me (below). I did add back the missing keyword function (count items in dictionary) to the example library that the test expected.

> daluu-mbp:phrrs daluu$ php src/StartRobotRemoteServer.php tests/test-libraries/ExampleLibrary.php 8270
> Looking for keyword definitions into: tests/test-libraries/ExampleLibrary.php
> List of defined keywords:
> - truth_of_life		--> from: tests/test-libraries/ExampleLibrary.php
> - count_items_in_directory		--> from: tests/test-libraries/ExampleLibrary.php
> - strings_should_be_equal		--> from: tests/test-libraries/ExampleLibrary.php
> Starting server on localhost:8270...
> 
> Fatal error: Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.' in /Users/daluu/work/other/phrrs/src/SocketInterface.php:69
> Stack trace:
> #0 /Users/daluu/work/other/phrrs/src/SocketInterface.php(69): DateTime->__construct()
> #1 /Users/daluu/work/other/phrrs/src/RobotRemoteServer.php(35): PhpRobotRemoteServer\SocketInterface->add('<?xml version="...')
> #2 /Users/daluu/work/other/phrrs/src/RobotRemoteServer.php(26): PhpRobotRemoteServer\RobotRemoteServer->start(Object(PhpRobotRemoteServer\SocketInterface), Object(PhpRobotRemoteServer\SocketInterface))
> #3 /Users/daluu/work/other/phrrs/src/BootstrapRobotRemoteServer.php(44): PhpRobotRemo in /Users/daluu/work/other/phrrs/src/SocketInterface.php on line 69
> daluu-mbp:phrrs daluu$

I think I also saw in code review a while back that you set a specific timezone or something like that, but maybe it was corrected later where I haven't yet reviewed. Not good to assume a specific timezone.

The failure causes the unit tests to fail as well. Looks like the failure causes the server to die at the first response it is sending back? I don't use PHP much these days and I've not worked with timezones in PHP, so you can look into this.

By the way, what platforms would this version of phrrs be able to run on (Linux, Mac, Windows)? I tested on Mac OS X 10.10.5, with PHP 5.5.27, PHPUnit 4.8.27, composer 1.2.1. From the readme, looks like you develop and tested on Ubuntu?

**Comment by jplambert** [comment]
Hi @daluu and thanks for the review,

Other people are using my version of phrrs; people I physically work with.

I stopped including the "count_items_in_directory" given its less deterministic nature. Since I have automated all the test cases, I felt it made more sense to use something like "truth_of_life" which always return 42. However, the canonical RF remote test should work as long as you provide the proper keyword implementations, they are just not included anymore in my branch. We could add them if you feel that it is important, we would have to update some tests but that would be fine. Or add it in a new sample keyword implementation, that would not be used in the automated test suite.

About the timezone stuff: yes when we started playing around with your code we encountered this kind of message about the timezone. So we added some sample timezone to get away with the warning/error. At the time it was meant as temporary, as a way to move forward. Later, though, it just happened that it was not necessary anymore. I can't say why, maybe it was because we moved away from Apache to PHP-CLI. In any case, we removed this piece of code setting the timezone and it should be in master.

And yes, this failure bluntly breaks the server at its first response. That is because it compute the current time to fill in the HTTP headers of the response.

So why are you getting this kind of error? I can't say for sure. I am using PHP 5.5.9 but under Linux Ubuntu. Maybe they do not handle this kind of stuff the same way? Like I would have a timezone set by default by not you? I think you should try setting up a timezone, either in the code or in the PHP configuration. In any case, I agree with you that we should not hardcode a timezone in the code.

At first sight I'd say that I have done nothing in my code that is specific to any platform, using only standard PHP libraries, so it should work on all the platforms. However I am no PHP expert, so I may got this wrong.

**Comment by daluu** [comment]
@jplambert would you guys happen to use docker or vagrant? Would be nice if I could get a config same as your system that I could deploy for testing (on Linux) while I try to test things out on Mac and Windows.

**Comment by jplambert** [comment]
@daluu sorry no. Most of our dev are under Linux, usually Ubuntu. Myself I am using a virtual machine that I have setup, but nothing fancy.

I will try to share later in the say the setup script we have written. It installs all the necessary packages: PHP-CLI, python, Robot Framework...

**Comment by jplambert** [comment]
@daluu Some project basics that include my version of phrrs:

composer.json:
```
{
    "name": "jplambert/tests-with-robot-framework-php",
    "require": {
        "jplambert/phrrs": "^1.1.2"
    }
}
```

install.sh:
```
#!/bin/sh

echo "Update apt-get"
sudo apt-get update -y
echo "-----> Done"
echo

echo "Install PHP-CLI"
sudo apt-get install -y php5-cli
echo "-----> Done"
echo

echo "Install Python 2.7 with pip"
sudo apt-get install -y python2.7 python-pip
echo "-----> Done"
echo

echo "Install Robot Framework"
pip install robotframework
echo "-----> Done"
echo

echo "Get composer"
wget https://getcomposer.org/composer.phar
echo "-----> Done"
echo

echo "Composer install"
php composer.phar install
echo "-----> Done"
echo
```

**Comment by daluu** [comment]
@jplambert btw, which version of Ubuntu are you and your devs typically using?

**Comment by jplambert** [comment]
@daluu We are typically using the latest LTS. I am currently using 14.04.

**Comment by daluu** [comment]
FYI, things look good and PR merged. But I'll follow up with issues supposedly addressed by the PR later after I find some more time to thoroughly verify them.

**Pull request merged**
